upgrade Dojo 1.0.0-alpha.9 (namespaces)

diff --git a/dojo/migrate b/dojo/migrate
--- a/dojo/migrate
+++ b/dojo/migrate
@@ -8,16 +8,41 @@ else
   export PROFILE="dev"
 fi
 
+export DOJO_PROFILE_FILE="dojo_$PROFILE.toml"
+
+if ! [ -x "$(command -v toml)" ]; then
+  echo 'Error: toml not instlaled! Instal with: cargo install toml-cli'
+  exit 1
+fi
+
+get_profile_env () {
+  local ENV_NAME=$1
+  local RESULT=$(toml get $DOJO_PROFILE_FILE --raw env.$ENV_NAME)
+  if [[ -z "$RESULT" ]]; then
+    >&2 echo "get_profile_env($ENV_NAME) not found! 👎"
+  fi
+  echo $RESULT
+}
+
 #-----------------
 # env setup
 #
-export WORLD_NAME_SEED="karatt"
-export MANIFEST_FILE_PATH="./manifests/$PROFILE/manifest.json"
-export BINDINGS_PATH="./bindings/typescript"
+export PROJECT_NAME=$(toml get $DOJO_PROFILE_FILE --raw world.name)
+export ACCOUNT_ADDRESS=${DOJO_ACCOUNT_ADDRESS:-$(get_profile_env "account_address")}
+export RPC_URL=${STARKNET_RPC_URL:-$(get_profile_env "rpc_url")}
+export WORLD_ADDRESS=$(get_profile_env "world_address")
+export MANIFEST_FILE_PATH="./manifests/$PROFILE/deployment/manifest.json"
 export CLIENT_PATH="../client/src/dojo/generated/$PROFILE"
-export PROJECT_NAME=$(toml get Scarb.toml --raw tool.dojo.world.name)
-export WORLD_ADDRESS=$(toml get Scarb.toml --raw profile.$PROFILE.tool.dojo.env.world_address)
-export RPC_URL=$(toml get Scarb.toml --raw profile.$PROFILE.tool.dojo.env.rpc_url)
+
+echo "------------------------------------------------------------------------------"
+echo ""
+echo "PROJECT: $PROJECT_NAME"
+echo "PROFILE: $PROFILE"
+echo "RPC_URL: $RPC_URL"
+echo "WORLD_ADDRESS: $WORLD_ADDRESS"
+echo "MANIFEST_FILE_PATH: $MANIFEST_FILE_PATH"
+echo "CLIENT_PATH: $CLIENT_PATH"
+echo ""
 
 if [[
   -z "$PROFILE" ||
@@ -28,12 +53,6 @@ if [[
   echo "! Missing data 👎"
   exit 1
 fi
-
-echo "------------------------------------------------------------------------------"
-echo ""
-echo "PROJECT: $PROJECT_NAME"
-echo "PROFILE: $PROFILE"
-echo ""
 
 #-----------------
 # build
@@ -50,10 +69,12 @@ echo ""
 # migrate
 #
 echo "------------------------------------------------------------------------------"
-echo "Migrating..."
-# sozo --profile $PROFILE migrate plan --world $WORLD_ADDRESS
+echo ">>> Migrate plan..."
+sozo -P $PROFILE migrate plan --world $WORLD_ADDRESS
 # exit 0
-sozo -P $PROFILE migrate apply --world $WORLD_ADDRESS --name $WORLD_NAME_SEED
+echo ">>> Migrate apply..."
+sozo -P $PROFILE migrate apply --world $WORLD_ADDRESS
+echo "👍"
 
 #-----------------
 # auth write
@@ -64,15 +85,20 @@ sozo -P $PROFILE migrate apply --world $WORLD_ADDRESS --name $WORLD_NAME_SEED
 #------------------------
 # copy manifest to client
 #
-echo "Copying manifest [$MANIFEST_FILE_PATH] to [$CLIENT_PATH/]"
+echo "------------------------------------------------------------------------------"
+echo ">>> Copying manifest [$MANIFEST_FILE_PATH] to [$CLIENT_PATH/]"
 mkdir -p $CLIENT_PATH
 cp $MANIFEST_FILE_PATH $CLIENT_PATH/
 
 #------------------------
 # generate components
 #
-cd ../client
-npm run create-components --profile=$PROFILE $RPC_URL $WORLD_ADDRESS
+if [[ "$PROFILE" == "dev" ]]; then
+  echo "------------------------------------------------------------------------------"
+  echo ">>> Generate sources..."
+  cd ../client
+  npm run create-components --profile=$PROFILE $RPC_URL $WORLD_ADDRESS
+fi
 
 # list copied files
 ls -ld $CLIENT_PATH/* | grep -E 'ts|json'
